config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
   resources :loans, only: [:new, :create]
  end

  get 'my_loans', to: 'loans#my_loans'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :loans
  mount_uploader :main_picture, PhotoUploader
  mount_uploader :second_picture, PhotoUploader
  mount_uploader :third_picture, PhotoUploader

  CATEGORIES = ["Occasions habillées", "Grossesse", "Sport", "Déguisements", "Voyages", "Tous les jours"].freeze
  ITEMS_TYPES = ["Robe", "Jupe", "Haut / T-shirt", "Pantalon", "Costume", "Chaussures", "Pull / sweat", "Manteau / Veste", "Masque"]
  GENDERS = ["Femme", "Homme", "Enfant", "Pour tout le monde"]
  COLORS = ["Noir", "Gris", "Blanc", "Rouge", "Rose", "Bleu", "Vert", "Jaune", "Orange", "Violet", "Multicolore"]
  SIZES = ["Unique", "XXS/32", "XS/34", "S/36", "M/38", "L/40", "XL/42", "XXL/44 et +"]
  ACCESSIBILITIES = ["Mes ami(e)s uniquement", "Mes ami(e)s et leurs ami(e)s", "Tout le monde"]
  EXCHANGES = ["d'un sourire", "d'un poème", "d'un diner", "des derniers potins", "d'une soirée à refaire le monde"]
  CAUTIONS = ["Non", "Oui, 10€", "Oui, 20€", "Oui, 30€", "Oui, 40€"]
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_many :loans
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :profile_picture, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :address, :office_address, :profile_picture])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :address, :office_address, :profile_picture])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    #@items = Item.all
    @items = policy_scope(Item)
  end

  def show
    @item = Item.find(params[:id])
    authorize @item
  end

  def loanrequest
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.save
    authorize @item
    redirect_to item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:category,:items_type,:color,:size,:main_picture,:second_picture,:third_picture,:accessibility,:description,:gender,:exchange,:cleaning,:guarantee,:contract)
  end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

  def my_loans
    @my_loans = current_user.items
    @my_borrows = current_user.loans
  end

  def show
    @loan = Loan.find(params[:id])
    authorize @loan
  end

  def new
    @item = Item.find(params[:item_id])
    @loan = Loan.new
    authorize @loan
  end

  def create
    @loan = Loan.new(loan_params)
    @item = Item.find(params[:item_id])
    @loan.item = @item
    @loan.user = current_user
    @loan.save
    authorize @loan
    redirect_to items_path
  end

  def edit
    @loan = Loan.find(params[:id])
  end

  def update
    @loan = Loan.find(params[:id])
    @loan.update(loan_params)
    redirect_to loan_path(@loan)
  end

  def destroy
    @loan = Loan.find(params[:id])
    @loan.destroy
    redirect_to loans_path
  end

  private

  def loan_params
    params.require(:loan).permit(:message, :start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/items/index.html.erb
<%= render '/components/top-navbar' %>

<div class="container">
  <div class="d-flex cards align-items-center">
    <% @items.each do |item| %>
      <div class="card">
        <%= link_to item_path(item.id) do %>
          <div>
            <%= cl_image_tag item.main_picture, height: 280, width: 280, crop: :fill %>
          </div>
        <% end %>
        <div class="card_info d-flex">
          <div>
            <p> Taille: <%= item.size %> </p>
          </div>
          <div>
            <%= cl_image_tag User.find(item.user_id).profile_picture, class:"avatar", height: 30, width: 30, crop: :fill %>
            <p class="no-pad"> <%= User.find(item.user_id).first_name.capitalize %> </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/loanrequest.html.erb
<!-- <div class="container"> -->
  <%#= simple_form_for(@item) do |f| %>
    <%#= f.input :message, label: "Votre message" %>
    <%#= f.submit "Faire une demande" %>
  <%# end %>
<!-- </div> -->

app/views/items/new.html.erb
<div class="container">
  <%= simple_form_for(@item) do |f| %>
    <%= f.input :category, label: "Categorie", collection: Item::CATEGORIES %>
    <%= f.input :items_type, label: "Type", collection: Item::ITEMS_TYPES %>
    <%= f.input :gender, label: "Genre", collection: Item::GENDERS %>
    <%= f.input :color, label: "Couleur", collection: Item::COLORS %>
    <%= f.input :size, label: "Taille", collection: Item::SIZES %>
    <%= f.input :accessibility, label: "A qui voulez-vous prêter cet article ?", collection: Item::ACCESSIBILITIES %>
    <%= f.input :description, label: "Description supplémentaire" %>
    <%= f.input :exchange, label: "En échange...", collection: Item::EXCHANGES  %>
    <%= f.input :cleaning, label: "Souhaitez-vous un passage en pressing avant restitution ?" %>
    <%= f.input :guarantee, label: "Souhaitez-vous demander une caution ?", collection: Item::CAUTIONS %>
    <%= f.input :contract, label: "Souhaitez-vous faire signer un contrat à l'emprunteur ?" %>
    <%= f.submit "Prêter" %>
  <% end %>
</div>


<!-- ajouter les inputs de photos :
    t.string "main_picture"
    t.string "second_picture"
    t.string "third_picture" -->

app/views/items/show.html.erb
<%= render '/components/top-navbar' %>

<div class="container">
  <div class="d-flex show_card">
    <div class="show_img">
      <% if @item.main_picture %>
        <%= cl_image_tag @item.main_picture, height: 500, width: 320, crop: :fill %>
      <% end %>
    </div>
    <div class= "show_details">
      <h1> <%= @item.items_type %> <%= @item.color %> (<%= @item.category %>) </h1>
      <div class="loaner d-flex">
        <div class="loaner_identity d-flex">
          <!-- <div> -->
            <%= cl_image_tag @item.user.profile_picture, class:"avatar"%>
          <!-- </div> -->
          <!-- <div> -->
            <p> Prêté par <%= @item.user.first_name.capitalize %></p>
          <!-- </div> -->
        </div>
        <div class="loaner_exchange">
          <p> <i class="fas fa-exchange-alt"></i> En échange <br> <%= @item.exchange %> </p>
        </div>
      </div>
      <div class="infos_requests d-flex">
        <div class ="infos">
          <p> Localisation : <%= @item.user.address %> </p>
          <p> Taille : <%= @item.size %> </p>
          <p> Couleur : <%= @item.color %> </p>
          <% if @item.description != "" %>
            <p> Bon à savoir : <%= @item.description %></p>
          <% else %>
            <p> <br> </p>
          <% end %>
        </div>
        <div class ="requests d-flex">
          <% if @item.contract %>
            <div class="request">
              <i class="fas fa-file-signature"></i>
              <p> Contrat </p>
            </div>
          <% end %>
          <% if @item.cleaning %>
            <div class="request">
              <i class="fas fa-tint"></i>
              <p> Pressing </p>
            </div>
          <% end %>
          <% if @item.guarantee != "Non" %>
            <div class="request">
              <i class="fas fa-euro-sign"></i>
              <p> Caution : <%= @item.guarantee.last(3) %> </p>
            </div>
          <% end %>
        </div>
      </div>
      <div class="main-btn-div">
        <%= link_to "Je veux l'emprunter" , new_item_loan_path(@item.id), class: "main-btn" %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocommode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/my_loans.html.erb
<h1> Coucou </h1>

app/views/loans/new.html.erb
<div class="container">
  <%= simple_form_for [@item, @loan] do |f| %>
    <%= f.input :message, label: "Votre message" %>
    <%= f.input :start_date, label: "Date de début" %>
    <%= f.input :end_date, label: "Date de fin" %>
    <%= f.submit "Envoyer la demande" %>
  <% end %>
</div>